Repository lblod/frontend-toezicht-abb, pull requests merged in 2023-06, with the labels that each got.

#40 Technical story/build and run maintenance
  .npmrc
  Dockerfile
  Dockerfile.prod
  package-lock.json
  package.json
Labels: Internal

#43 Downgrade Ember Data to v4.11
  package-lock.json
  package.json
Labels: bug

#44 Bump ember-submission-form-fields v2.11.0
  package-lock.json
  package.json
Labels: dependencies, Internal
